sudo: false
env:
    global:
        - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgfortran.so.3
addons:
    apt:
        packages:
            - gfortran
language: python
matrix:
  include:
      - python: "2.7"
        env: 
        - PYTHON_VERSION="2.7"
        - NOSE_ARGS="-v --no-skip --with-cov --cov pydisdrometer pydisdrometer"
        - COVERALLS="true"

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
install: source continuous_integration/install.sh

script:
    - nosetests $NOSE_ARGS 
after_success:
    - coveralls
