sudo: false
env:
    global:
        - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgfortran.so.3
addons:
    apt:
        packages:
            - gfortran
language: python

matrix:
  include:
      - python: "2.7"
        env: 
        - PYTHON_VERSION="2.7"
        - NOSE_ARGS="-v --no-skip --with-cov --cov pydisdrometer pydisdrometer"
        - COVERALLS="true"
      - python: "3.4"
        env: 
        - PYTHON_VERSION="3.4"
        - NOSE_ARGS="-v --no-skip --with-cov --cov pydisdrometer pydisdrometer"
        - COVERALLS="true"
      - python: "3.5"
        env: 
        - PYTHON_VERSION="3.5"
        - NOSE_ARGS="-v --no-skip --with-cov --cov pydisdrometer pydisdrometer"
        - COVERALLS="true"


before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

install: source continuous_integration/install.sh

script: eval xvfb-run nosetests $NOSE_ARGS

after_success:
    - coveralls
